carts/urls.py
from django.urls import path
from .views import view, update_to_cart

app_name = 'carts'
urlpatterns = [
    path('view/', view, name='view'),
    path('cart/<slug:slug>/', update_to_cart, name='update_to_cart'),

 ]

eCommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import  static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('', include('carts.urls', namespace='carts')),
]

# in development phase ..

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import home, single, search

app_name = 'products'

urlpatterns = [
    path('', home, name='home'),
    path('s/', search, name='search'),
    path('products/<slug:slug>/', single, name='detail'),
]

carts/models.py
from django.db import models
from products.models  import  Product
class Cart(models.Model):
    products = models.ManyToManyField(Product)
    total = models.DecimalField(decimal_places=2, max_digits=10, default=0.00)
    timestamp = models.DateTimeField(auto_now=False,auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return f"Cart id: {self.id}"

products/models.py
from django.db import models
from django.urls import reverse


class Product(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(null=True)
    price = models.DecimalField(decimal_places=2, max_digits=10,default=25.89)
    sale_price = models.DecimalField(decimal_places=2, max_digits=10, null=True, blank=True)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    class Meta:
        unique_together = ('title','slug')

    def get_absolute_url(self):
        return reverse('products:detail', kwargs={'slug':self.slug})


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/images/')
    thumbnail = models.BooleanField(default=False)
    featured = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.product.title

carts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from products.models import Product
from .models import Cart

def view(request):
    cart = Cart.objects.all()[0]
    context = {'cart':cart}
    template = 'cart/view.html'
    return render(request, template, context)

def update_to_cart(request,slug):
    cart = Cart.objects.all()[0]
    try:
        product = Product.objects.get(slug=slug)
    except Product.DoesNotExist:
        pass
    except:
        pass


    if not product in cart.products.all():
        cart.products.add(product)
    else:
        cart.products.remove(product)
    new_total = 0.00
    for item in cart.products.all():
        new_total += float(item.price)
    cart.total = new_total
    cart.save()
    return redirect("carts:view")

products/views.py
import os

from django.shortcuts import render
from .models import ProductImage, Product
from django.http import Http404
def home(request):
    products = Product.objects.all()
    context = {'products':products}
    return render(request, 'products/home.html', context)

def single(request,slug):
    try:
        product = Product.objects.get(slug=slug)
        images = ProductImage.objects.filter(product=product)

        #images = product.productimage_set.all()
        # new_img = []
        # for img in images:
        #     new_img.append("media/"+ str(img.image))
        # print(type(new_img))
        # data = str(new_img)
        # data = data
        context = {'product':product, 'images':images}
    except Product.DoesNotExist:
        raise Http404
    return render(request, 'products/detail.html', context)

def search(request):
    try:
        q = request.GET.get('q')
    except:
        q = None
    if q:
        products = Product.objects.filter(title__icontains=q)
        context = {'query':q, 'products':products}

        template = 'products/search.html'
    else:
        context = {}
        template = 'products/home.html'
    return render(request, template, context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    {% include 'nav.html' %}
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/cart/view.html
{% extends 'base.html' %}

{% block content %}
<div class="col-sm-8 col-sm-offset-2">
    <table class="table">
        <thead>
        <th>Item</th>
        <th>Price</th>
        <th></th>
        </thead>
        <tfoot>
        <tr>
            <td></td>
            <td></td>
            <td>Total: {{ cart.total }}</td>
        </tr>
        </tfoot>
        {% for item in cart.products.all %}
        <tr>
            <td>{{ item }}</td>
            <td>{{item.price}}</td>
            <td> <a href="{% url 'carts:update_to_cart' item.slug %}">Remove</a></td>

        </tr>

        {% endfor %}
    </table>
</div>

{% endblock %}

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'products:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'carts:view' %}">Go to Cart</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" action="/s/">
      <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

templates/products/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="page-header">
  <h1>{{ product.title }}</h1>
</div>
<div class="float-right">
    <h1><a href="{% url 'carts:update_to_cart' product.slug %}">Add to cart</a></h1>
</div>
{% for img in images %}
    <img src="media/{{img.image }}" alt="" width="100" height="100">
{% endfor %}



<h5>Read more about the product info:</h5>
<p>
    <p>
    {{ product.description }}
</p>
</p>

{% endblock %}

templates/products/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h2>List of all the products from my website!!</h2>

<div class="row">
    {% for item in products %}
    <div class="col-sm-4" >
            <div class="thumbnail">
                {% if item.productimage_set.all %}

                        {% for data in item.productimage_set.all %}
                            {% if data.featured %}
                                 <img src="media/{{ MEDIA_URL }}{{data.image}}" alt="" width="100" height="100">
                            {% endif %}
                        {% endfor %}
                {% else %}
                        <img src="{% static 'img/empty.jpg' %}" alt="" width="100" height="100">
                {% endif %}

                    <div class="caption">
                        <a href="{{ item.get_absolute_url }}" class="card-title"> <h3>{{ item.title }}</h3></a>
                            <p>{{ item.description|truncatewords:15 }}</p>
                        <p><a href="{{ item.get_absolute_url }}" class="btn btn-info mr-2"
                              role="button">View</a><a href="{% url 'carts:update_to_cart' item.slug %}" class="btn btn-danger" role="button"
                        >Add to Cart</a></p>
                    </div>
            </div>
    </div>

    {% cycle "" "" "</div><br/><hr/><div class='row'>" %}

        {% endfor %}
</div>
{% endblock %}

templates/products/search.html
{% extends 'base.html' %}

{% block content %}
<h3>Searched for:{{ query }} </h3>
{% for data in products %}
<h5>{{ data.description }}</h5>
{% endfor %}
    <p>Go and get that product here: <a href="{% url 'products:home' %}">Click</a></p>

{% endblock %}